-- Create Table
CREATE TABLE movies (
    id SERIAL PRIMARY KEY,
    movie_name VARCHAR,
    directed_by VARCHAR,
    story_by VARCHAR,
    based_on VARCHAR,
    produced_by VARCHAR,
    starring VARCHAR,
    music_by VARCHAR,
    production_company VARCHAR,
    distributed_by VARCHAR,
    release_dates VARCHAR,
    running_time VARCHAR,
    country VARCHAR,
    language VARCHAR,
    budget VARCHAR,
    box_office VARCHAR,
    narrated_by VARCHAR,
    cinematography VARCHAR,
    release_date VARCHAR,
    written_by VARCHAR,
    edited_by VARCHAR,
    screenplay_by VARCHAR,
    countries VARCHAR,
    production_companies VARCHAR
);
